### ISSUE TITLE
No symbol named `global-set-key'

### ISSUE THREAD

**Issue by NalaGinrut** [spk121/zile#1] opened 2017-04-26 06:31 UTC
I run zile-on-guile successfully on guile-2.2 with patches from me (I may send them later).
But it complains a warning:

zile.scm:129:2: warning: possibly unbound variable `global-set-key'

I think `global-set-key' is in Emacs, I never saw it in Guile. Should we implement it? 
@spk121

**Comment by spk121** [comment] 2017-04-27 17:14
There is a global-set-key in emacs.  But, I think the problem is that bind.c's "set-key" should have been exported as "global-set-key", instead of "set-key".

**Comment by NalaGinrut** [comment] 2017-04-28 08:30
ok, do you need patch for this issue? And I have other patch to make it work for the latest guile, since something was obsoleted out. I can send them all.

**Comment by amirouche** [comment] 2017-04-28 17:19
@NalaGinrut please make a PR!

**Comment by spk121** [comment] 2017-04-28 17:22
@NalaGinrut I'd be happy to pull in any patches you have.  Otherwise, I'll fix it, but, not this week.

**Comment by NalaGinrut** [comment] 2017-04-29 19:20
I failed to find a way to export global-set-key properly. It seems that all symbols in the elf need to export to Guile environment, usually there'd be dynamic-call. But I've no idea how to export symbols from a elf file rather than .so

**Comment by spk121** [comment] 2017-05-05 06:45
I think this is fixed in 1ac5832bad4f50d7d79b70686f22b9205a7cf7ac

**Closed as completed** 2017-05-05 21:51 UTC
